import React from "react";

const Articles = [

    {
        category: "Religion",
        name: "freewill_&_predestination",
        title: "Is divine predestination compatible with human freewill?",
        date: "9th Aug 2022",
        time_to_read: "5 min read",
        logo_url: "/Logos/religious-icons.jpg",
        img_url: "/ArticleImages/puppet.jpeg",
        p1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, officia doloremque pariatur explicabo mollitia amet quia necessitatibus repellat accusamus harum, quisquam quod. Tempore ipsa voluptates quod ab delectus dolore at? Quo minima veritatis accusantium iure, nobis asperiores unde fuga dignissimos beatae, atque distinctio eligendi quidem! Assumenda non optio dicta deserunt quaerat rem eos. Maiores velit nesciunt commodi odio minima unde. Dolore, porro ipsum illum non, voluptatem voluptatibus doloribus ratione accusantium sint incidunt, accusamus quasi. Veritatis modi, reprehenderit, reiciendis ut at laudantium officiis natus consequuntur unde harum eum veniam. Aliquid, culpa. Sit aliquam autem tempora excepturi esse ut nostrum eaque a, fugit minima qui officia nihil aperiam dolores fugiat ratione eius dolorem? Hic, velit rerum magni assumenda illum culpa animi doloremque! Asperiores, facere? Placeat, hic et! Autem quos necessitatibus animi quam optio et odit, veniam tempora ad doloremque ullam eius ex voluptates illo velit quisquam. Nisi consequuntur iste aut repudiandae quia? Expedita eos maxime ea exercitationem debitis similique accusantium illum delectus eligendi. Fugiat praesentium rerum sint quasi, fugit magni omnis et aut quia nostrum cupiditate itaque quidem, officia error quisquam repellendus. Mollitia debitis provident incidunt necessitatibus, libero, fugit unde quas minima assumenda repellat consequuntur architecto quisquam, ea blanditiis! Harum alias veritatis mollitia ex, a autem, enim impedit, sequi at dolorem rem."
    },

    {
        category: "Metaphysics",
        name: "kalam_criticism",
        title: "A critique of The Kalam Cosmological Argument",
        date: "9th Aug 2022",
        time_to_read: "5 min read",
        logo_url: "/Logos/metaphysics-logo.png",
        img_url: "/ArticleImages/kalam.jpg",
        p1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, officia doloremque pariatur explicabo mollitia amet quia necessitatibus repellat accusamus harum, quisquam quod. Tempore ipsa voluptates quod ab delectus dolore at? Quo minima veritatis accusantium iure, nobis asperiores unde fuga dignissimos beatae, atque distinctio eligendi quidem! Assumenda non optio dicta deserunt quaerat rem eos. Maiores velit nesciunt commodi odio minima unde. Dolore, porro ipsum illum non, voluptatem voluptatibus doloribus ratione accusantium sint incidunt, accusamus quasi. Veritatis modi, reprehenderit, reiciendis ut at laudantium officiis natus consequuntur unde harum eum veniam. Aliquid, culpa. Sit aliquam autem tempora excepturi esse ut nostrum eaque a, fugit minima qui officia nihil aperiam dolores fugiat ratione eius dolorem? Hic, velit rerum magni assumenda illum culpa animi doloremque! Asperiores, facere? Placeat, hic et! Autem quos necessitatibus animi quam optio et odit, veniam tempora ad doloremque ullam eius ex voluptates illo velit quisquam. Nisi consequuntur iste aut repudiandae quia? Expedita eos maxime ea exercitationem debitis similique accusantium illum delectus eligendi. Fugiat praesentium rerum sint quasi, fugit magni omnis et aut quia nostrum cupiditate itaque quidem, officia error quisquam repellendus. Mollitia debitis provident incidunt necessitatibus, libero, fugit unde quas minima assumenda repellat consequuntur architecto quisquam, ea blanditiis! Harum alias veritatis mollitia ex, a autem, enim impedit, sequi at dolorem rem."
    },
    {
        category: "Ethics",
        name: "eutyphro_dilemma",
        title: "The Euthyphro dilemma",
        date: "9th Aug 2022",
        time_to_read: "5 min read",
        logo_url: "/Logos/metaethics-logo.png",
        img_url: "/ArticleImages/eutyphro.jpeg",
        p1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, officia doloremque pariatur explicabo mollitia amet quia necessitatibus repellat accusamus harum, quisquam quod. Tempore ipsa voluptates quod ab delectus dolore at? Quo minima veritatis accusantium iure, nobis asperiores unde fuga dignissimos beatae, atque distinctio eligendi quidem! Assumenda non optio dicta deserunt quaerat rem eos. Maiores velit nesciunt commodi odio minima unde. Dolore, porro ipsum illum non, voluptatem voluptatibus doloribus ratione accusantium sint incidunt, accusamus quasi. Veritatis modi, reprehenderit, reiciendis ut at laudantium officiis natus consequuntur unde harum eum veniam. Aliquid, culpa. Sit aliquam autem tempora excepturi esse ut nostrum eaque a, fugit minima qui officia nihil aperiam dolores fugiat ratione eius dolorem? Hic, velit rerum magni assumenda illum culpa animi doloremque! Asperiores, facere? Placeat, hic et! Autem quos necessitatibus animi quam optio et odit, veniam tempora ad doloremque ullam eius ex voluptates illo velit quisquam. Nisi consequuntur iste aut repudiandae quia? Expedita eos maxime ea exercitationem debitis similique accusantium illum delectus eligendi. Fugiat praesentium rerum sint quasi, fugit magni omnis et aut quia nostrum cupiditate itaque quidem, officia error quisquam repellendus. Mollitia debitis provident incidunt necessitatibus, libero, fugit unde quas minima assumenda repellat consequuntur architecto quisquam, ea blanditiis! Harum alias veritatis mollitia ex, a autem, enim impedit, sequi at dolorem rem."

    },
    {
        category: "Consciousness",
        name: "materialism_defense",
        title: "A defense of materialist theories of consciousness",
        date: "9th Aug 2022",
        time_to_read: "5 min read",
        logo_url: "/Logos/mind-logo.jpg",
        img_url: "/ArticleImages/materialism.jpeg",
        p1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, officia doloremque pariatur explicabo mollitia amet quia necessitatibus repellat accusamus harum, quisquam quod. Tempore ipsa voluptates quod ab delectus dolore at? Quo minima veritatis accusantium iure, nobis asperiores unde fuga dignissimos beatae, atque distinctio eligendi quidem! Assumenda non optio dicta deserunt quaerat rem eos. Maiores velit nesciunt commodi odio minima unde. Dolore, porro ipsum illum non, voluptatem voluptatibus doloribus ratione accusantium sint incidunt, accusamus quasi. Veritatis modi, reprehenderit, reiciendis ut at laudantium officiis natus consequuntur unde harum eum veniam. Aliquid, culpa. Sit aliquam autem tempora excepturi esse ut nostrum eaque a, fugit minima qui officia nihil aperiam dolores fugiat ratione eius dolorem? Hic, velit rerum magni assumenda illum culpa animi doloremque! Asperiores, facere? Placeat, hic et! Autem quos necessitatibus animi quam optio et odit, veniam tempora ad doloremque ullam eius ex voluptates illo velit quisquam. Nisi consequuntur iste aut repudiandae quia? Expedita eos maxime ea exercitationem debitis similique accusantium illum delectus eligendi. Fugiat praesentium rerum sint quasi, fugit magni omnis et aut quia nostrum cupiditate itaque quidem, officia error quisquam repellendus. Mollitia debitis provident incidunt necessitatibus, libero, fugit unde quas minima assumenda repellat consequuntur architecto quisquam, ea blanditiis! Harum alias veritatis mollitia ex, a autem, enim impedit, sequi at dolorem rem."

    },

    {
        category: "Epistemology",
        name: "solipsism_refutation",
        title: "Can solipsism be refuted?",
        date: "9th Aug 2022",
        time_to_read: "5 min read",
        logo_url: "/epistemology-logo.jpg",
        img_url: "/ArticleImages/solipsism.png",
        p1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, officia doloremque pariatur explicabo mollitia amet quia necessitatibus repellat accusamus harum, quisquam quod. Tempore ipsa voluptates quod ab delectus dolore at? Quo minima veritatis accusantium iure, nobis asperiores unde fuga dignissimos beatae, atque distinctio eligendi quidem! Assumenda non optio dicta deserunt quaerat rem eos. Maiores velit nesciunt commodi odio minima unde. Dolore, porro ipsum illum non, voluptatem voluptatibus doloribus ratione accusantium sint incidunt, accusamus quasi. Veritatis modi, reprehenderit, reiciendis ut at laudantium officiis natus consequuntur unde harum eum veniam. Aliquid, culpa. Sit aliquam autem tempora excepturi esse ut nostrum eaque a, fugit minima qui officia nihil aperiam dolores fugiat ratione eius dolorem? Hic, velit rerum magni assumenda illum culpa animi doloremque! Asperiores, facere? Placeat, hic et! Autem quos necessitatibus animi quam optio et odit, veniam tempora ad doloremque ullam eius ex voluptates illo velit quisquam. Nisi consequuntur iste aut repudiandae quia? Expedita eos maxime ea exercitationem debitis similique accusantium illum delectus eligendi. Fugiat praesentium rerum sint quasi, fugit magni omnis et aut quia nostrum cupiditate itaque quidem, officia error quisquam repellendus. Mollitia debitis provident incidunt necessitatibus, libero, fugit unde quas minima assumenda repellat consequuntur architecto quisquam, ea blanditiis! Harum alias veritatis mollitia ex, a autem, enim impedit, sequi at dolorem rem."

    },
    {
        category: "Existentialism",
        name: "atheism_nihilism_link",
        title: "Does atheism lead to nihilism?",
        date: "9th Aug 2022",
        time_to_read: "5 min read",
        logo_url: "/Logos/existentialism-logo.jpg",
        img_url: "/ArticleImages/nihilism.jpg",
        p1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempore illo minus neque, atque harum ab aut nulla adipisci dolore, numquam maiores consequuntur laborum, non ullam id accusamus perspiciatis quod magnam? Atque perspiciatis tenetur deserunt ex soluta est sint nemo corporis architecto, neque hic incidunt facilis autem consectetur nesciunt voluptas. Quas cupiditate assumenda quasi voluptatum, non qui hic porro? Vel, veritatis. Inventore soluta, dicta assumenda sed odio unde perspiciatis doloribus quisquam, natus quidem magnam ad iusto architecto adipisci, enim omnis doloremque.",
        p3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus, officia doloremque pariatur explicabo mollitia amet quia necessitatibus repellat accusamus harum, quisquam quod. Tempore ipsa voluptates quod ab delectus dolore at? Quo minima veritatis accusantium iure, nobis asperiores unde fuga dignissimos beatae, atque distinctio eligendi quidem! Assumenda non optio dicta deserunt quaerat rem eos. Maiores velit nesciunt commodi odio minima unde. Dolore, porro ipsum illum non, voluptatem voluptatibus doloribus ratione accusantium sint incidunt, accusamus quasi. Veritatis modi, reprehenderit, reiciendis ut at laudantium officiis natus consequuntur unde harum eum veniam. Aliquid, culpa. Sit aliquam autem tempora excepturi esse ut nostrum eaque a, fugit minima qui officia nihil aperiam dolores fugiat ratione eius dolorem? Hic, velit rerum magni assumenda illum culpa animi doloremque! Asperiores, facere? Placeat, hic et! Autem quos necessitatibus animi quam optio et odit, veniam tempora ad doloremque ullam eius ex voluptates illo velit quisquam. Nisi consequuntur iste aut repudiandae quia? Expedita eos maxime ea exercitationem debitis similique accusantium illum delectus eligendi. Fugiat praesentium rerum sint quasi, fugit magni omnis et aut quia nostrum cupiditate itaque quidem, officia error quisquam repellendus. Mollitia debitis provident incidunt necessitatibus, libero, fugit unde quas minima assumenda repellat consequuntur architecto quisquam, ea blanditiis! Harum alias veritatis mollitia ex, a autem, enim impedit, sequi at dolorem rem."
    }

]

export default Articles;